name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Tarball
        run: tar -czf app.tar.gz package.json package-lock.json server.js models Dockerfile docker-compose.yml

      - name: Copy Tarball to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "app.tar.gz"
          target: "~/studentdetails"

      - name: Deploy Application
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/studentdetails
            # Extract valid source code
            tar -xzf app.tar.gz
            rm app.tar.gz
            
            # Setup env
            echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" > .env
            
            # Build the image manually
            docker build -t studentdetails:latest .
            
            # Stop old containers to free up ports
            docker-compose down || true
            
            # Start containers
            docker-compose up -d
